# Generated by Django 5.2.10 on 2026-03-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_bio_user_facebook_user_github_user_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', upload_to='profile_pics/'),
        ),
    ]
